# Generated by Django 2.2 on 2019-04-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='showAlways',
            new_name='show_always',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='date_created',
            field=models.DateField(verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='date_doing',
            field=models.DateField(null=True, verbose_name='date doing'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='date_due',
            field=models.DateField(verbose_name='date due'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.CharField(max_length=42),
        ),
    ]
