# Generated by Django 3.0.2 on 2020-02-24 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20200223_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
