# Generated by Django 3.0.2 on 2020-02-24 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'Invited'), (1, 'Active'), (2, 'Owner')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Profile')),
            ],
        ),
    ]
