# Generated by Django 3.0.2 on 2020-02-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('meeting', models.IntegerField()),
            ],
        ),
    ]
