# Generated by Django 3.0.3 on 2020-02-27 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_timeavailability'),
        ('meeting', '0006_projectmeeting'),
    ]

    operations = [
    ]
