# Generated by Django 3.0.2 on 2020-03-06 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_merge_20200227_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=0, max_length=200)),
                ('location', models.CharField(default=0, max_length=200)),
                ('optional_members', models.CharField(default='None', max_length=200)),
                ('description', models.CharField(default='No description available', max_length=200)),
                ('project', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='meeting.Project')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectMeeting',
        ),
    ]
