# Generated by Django 3.0.2 on 2020-03-12 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_auto_20200311_2209'),
        ('meeting', '0009_auto_20200310_2229'),
    ]

    operations = [
    ]
