# Generated by Django 3.0.2 on 2020-03-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_auto_20200311_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='end_date',
            field=models.DateField(default='0000/00/00'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_date',
            field=models.DateField(default='0000/00/00'),
        ),
    ]
