# Generated by Django 3.0.2 on 2020-04-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0014_meetingtime_hasvoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='final_date',
            field=models.DateTimeField(default='NULL'),
        ),
    ]
