# Generated by Django 3.0.3 on 2020-04-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0014_meetingtime_hasvoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='org',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
