# Generated by Django 3.0.3 on 2020-04-16 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0014_meetingtime_hasvoted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingtime',
            name='hasVoted',
        ),
        migrations.RemoveField(
            model_name='meetingtime',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='meeting_time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='state',
            field=models.IntegerField(choices=[(0, 'Close'), (1, 'Open'), (2, 'Done'), (3, 'Review'), (4, 'Revote'), (5, 'No Vote')], default=1),
        ),
        migrations.CreateModel(
            name='MeetingTimeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('vote_count', models.IntegerField(default=0)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting')),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='meeting_time_option',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='meeting.MeetingTimeOption'),
        ),
    ]
