# Generated by Django 3.0.2 on 2020-04-19 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0015_auto_20200419_0359'),
        ('meeting', '0015_profile_org'),
    ]

    operations = [
    ]
