# Generated by Django 3.0.3 on 2020-04-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0015_auto_20200416_0242'),
        ('meeting', '0016_merge_20200419_0409'),
    ]

    operations = [
    ]
