# Generated by Django 3.0.2 on 2020-04-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0016_auto_20200409_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='final_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
