# Generated by Django 3.0.2 on 2020-04-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0017_auto_20200409_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='final_date',
            field=models.DateTimeField(null=True),
        ),
    ]
