# Generated by Django 3.0.2 on 2020-04-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0019_auto_20200409_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='final_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
