# Generated by Django 3.0.2 on 2020-04-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0020_auto_20200410_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='final_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
