# Generated by Django 3.0.2 on 2020-04-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0021_auto_20200410_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='final_date',
            field=models.CharField(default='TBA', max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(default='TBA', max_length=200),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='optional_members',
            field=models.CharField(default='Required', max_length=200),
        ),
    ]
